name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
      
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run fastapi web-server
        run: |
          uvicorn main:app &

      - name: Run JMeter Action Load Testing
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: JMeter/simpleFastAPILoadTest.jmx
          outputReportsFolder: simpleFastAPILoadTestReports/
          args: "--loglevel INFO -q JMeter/simpleFastAPI.properties"

      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: simpleFastAPILoadTestReports
          path: simpleFastAPILoadTestReports/
