name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
      
    steps:
      - uses: actions/checkout@v2

      - name: Run fastapi docker
        run: |
          uvicorn main:app &docker compose up

      - name: Run JMeter Action Load Testing
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: JMeter/simpleFastAPILoadTest.jmx
          outputReportsFolder: simpleFastAPILoadTestReports/
          args: "--loglevel INFO -q JMeter/simpleFastAPI.properties"

      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: simpleFastAPILoadTestReports
          path: simpleFastAPILoadTestReports/
